// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using Application.ApplicationLayer.ViewModels;
using GalaSoft.MvvmLight.Helpers;
using UILayer.UILayer.CollectionViews;
using UILayer.UILayer.CollectionViews.Cells;
using UILayer.UILayer.Common;
using UILayer.UILayer.Common.Navigation;
using UILayer.UILayer.Common.UI;
using UIKit;

namespace UILayer.UILayer.Views
{
	public partial class FeedViewController : UIViewController, IBinder, IStyler
	{
        private readonly FeedViewModel dataContext;

        private readonly FeedCollectionViewSource source;

        public List<Binding> Bindings { get; set; }

        public FeedViewController (IntPtr handle) : base (handle)
		{
            dataContext = new FeedViewModel(CurrentUser.UserId);

            source = new FeedCollectionViewSource(CurrentUser.UserId);
            source.LoadData(dataContext.Posts.ToList());
           
            Bindings = new List<Binding>();
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            SetBindings();
            SetCommands();
            BaseStyling();
            EventStyling();

            NavigationBar.Set(this, HomeButton, FriendsButton, AddPostButton, ProfileButton);

            FeedCollectionView.RegisterNibForCell(FeedCollectionViewCell.Nib, FeedCollectionViewCell.Key);

            var layout = new UICollectionViewFlowLayout();
            layout.ItemSize = new CoreGraphics.CGSize(388, 500);

            FeedCollectionView.SetCollectionViewLayout(layout, true);

            FeedCollectionView.Source = source;
            FeedCollectionView.ReloadData();
        }

        public void SetBindings()
        {
            source.OnItemChanged += (o, e) =>
            {
                source.LoadData(dataContext.Posts.ToList());

                FeedCollectionView.ReloadData();
            };
        }

        public void SetCommands()
        {
        }

        public void BaseStyling()
        {
        }

        public void EventStyling()
        {
        }
    }
}
