// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Application.ApplicationLayer.ViewModels;
using GalaSoft.MvvmLight.Helpers;
using UILayer.UILayer.Common;
using UILayer.UILayer.Common.Navigation;
using UILayer.UILayer.Common.UI;
using UIKit;

namespace UILayer.UILayer.Views
{
	public partial class RegisterViewController : UIViewController, IBinder, IStyler
	{
        private readonly RegisterViewModel dataContext;

        public List<Binding> Bindings { get; set; }

        public RegisterViewController (IntPtr handle) : base (handle)
		{
            Bindings = new List<Binding>();
            dataContext = new RegisterViewModel();
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            SetBindings();
            SetCommands();
            BaseStyling();
            EventStyling();
        }

        public void BaseStyling()
        {
            Styler.SetTextColor(ErrorLabel, UIColor.Red);
            Styler.SetBorderRadius(AddImageButton, 20f);
            Styler.SetShadows(AddImageButton, UIColor.Black, 2, 3, 2f);
            Styler.SetTextColor(AddImageButton, UIColor.Clear);

            Styler.SetShadows(RegisterButton, UIColor.Black, 2, 3, 3f);
        }

        public void EventStyling()
        {
        }

        public void SetBindings()
        {
            Bindings.Add(this.SetBinding
                (
                 () => dataContext.Username,
                 () => UsernameTextField.Text,
                 BindingMode.TwoWay
                ));

            Bindings.Add(this.SetBinding
                (
                 () => dataContext.Email,
                 () => EmailTextField.Text,
                 BindingMode.TwoWay
                ));

            Bindings.Add(this.SetBinding
                (
                 () => dataContext.UserTag,
                 () => UserTagTextField.Text,
                 BindingMode.TwoWay
                ));

            Bindings.Add(this.SetBinding
                (
                 () => dataContext.Password,
                 () => PasswordTextField.Text,
                 BindingMode.TwoWay
                ));

            Bindings.Add(this.SetBinding
                (
                 () => dataContext.RegisterSucceeded,
                 () => ErrorLabel.Text
                ).ConvertSourceToTarget((s) =>
                {
                    if (s)
                    {
                        CurrentUser.UserId = dataContext.UserId;
                        Navigator.Navigate(this, CtrConst.FeedController);

                        return ErrorLabel.Text = string.Empty;
                    }
                    else
                    {
                        if (string.IsNullOrWhiteSpace(UsernameTextField.Text) && string.IsNullOrWhiteSpace(PasswordTextField.Text)) return string.Empty;

                        return ErrorLabel.Text = "User already exists!";
                    }
                }));
        }

        public void SetCommands()
        {
            RegisterButton.SetCommand(dataContext.RegisterCommand, this.SetBinding(() => UsernameTextField.Text));
        }
    }
}
